language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.1
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"